/*% if (feature.T_EntitiesInformation) { %*/
package es.udc.lbd.gema.lps.component.entities_information.custom;

import java.util.List;

public class EntityPropertyJSON {

    private String name;
    private String type;
    private String simpleType;
    private boolean collection;
    private boolean autogenerated;
    private List<EntityPropertyConstraintJSON> constraints;

    public EntityPropertyJSON() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSimpleType() {
        return simpleType;
    }

    public void setSimpleType(String simpleType) {
        this.simpleType = simpleType;
    }

    public boolean isCollection() {
        return collection;
    }

    public void setCollection(boolean collection) {
        this.collection = collection;
    }

    public boolean isAutogenerated() {
        return autogenerated;
    }

    public void setAutogenerated(boolean autogenerated) {
        this.autogenerated = autogenerated;
    }

    public List<EntityPropertyConstraintJSON> getConstraints() {
        return constraints;
    }

    public void setConstraints(List<EntityPropertyConstraintJSON> constraints) {
        this.constraints = constraints;
    }

    @Override
    public String toString() {
        return "EntityPropertyJSON [name=" + name + ", type=" + type + ", simpleType=" + simpleType + ", collection="
                + collection + ", autogenerated=" + autogenerated + ", constraints=" + constraints + "]";
    }
}
/*% } %*/
